# Generated by Django 6.0.4 on 2026-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_quoterequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='cart_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw cart data for 1-click reorder'),
        ),
    ]
