# Generated by Django 6.0.4 on 2026-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_quoterequest_cart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set by Admin in KES', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final total including delivery', max_digits=12, null=True),
        ),
    ]
