# Generated by Django 6.0.4 on 2026-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contractorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True when M-Pesa webhook confirms payment'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='mpesa_receipt',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code', max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('invoiced', 'Invoiced'), ('paid', 'Paid/Processing')], default='pending', max_length=20),
        ),
    ]
