# Generated by Django 6.0.4 on 2026-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_quoterequest_is_paid_quoterequest_mpesa_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='vehicle_reg',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vehicle Plate Number'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Price Quoted (Waiting for Approval)'), ('accepted', 'Approved by Contractor'), ('paid', 'Paid - Awaiting Dispatch'), ('loading', 'Loading at Warehouse'), ('dispatched', 'In Transit'), ('delivered', 'Delivered to Site')], default='pending', max_length=20),
        ),
    ]
