# Generated by Django 6.0.4 on 2026-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_quoterequest_driver_name_quoterequest_driver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Not Submitted)'), ('pending', 'Pending Review'), ('reviewed', 'Price Quoted (Waiting for Approval)'), ('accepted', 'Approved by Contractor'), ('paid', 'Paid - Awaiting Dispatch'), ('loading', 'Loading at Warehouse'), ('dispatched', 'In Transit'), ('delivered', 'Delivered to Site')], default='pending', max_length=20),
        ),
    ]
