# Generated by Django 6.0.4 on 2026-05-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_quoterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is the main owner account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='store.contractorprofile'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Company Owner (Full Access)'), ('foreman', 'Site Foreman (Ordering & Drafts Only)'), ('accountant', 'Accountant (Billing & Payments Only)')], default='owner', max_length=20),
        ),
    ]
